### PR TITLE
add return receipt message, tx log updates, geo region update

### PR DESCRIPTION
**Pull request by remyers**
I didn't retest SMS yet, but did a lot of testing with goTenna and seems to be working.

### CODE REVIEW

**Comment by remyers** [comment]
Step 1: broadcast from mesh only connected node:



Step 2: Internet connected node uploads transaction to the Bitcoin network (in mem pool) and sends private/encrypted message back to mesh only node that originated the transaction:



Step 3: Internet connected node confirms the transaction included in a block and sends a private/encrypted message back to the mesh only node that originated the transaction:

screenshot_20181107-093644

Updated list of geographic regions, also fixed a bug where value selected in the UI was not used to set the radio:

screenshot nov 7 2018 09_57_19

**Comment by remyers** [comment]
@SamouraiDev is there anything I can do to help you review this pull request? maybe break it up into a less monolithic PR?

**Comment by SamouraiDev** [comment]
I need to find the time to test it again. The first time I tested I was getting an error. IIRC, it was related to region selection.

**Comment by remyers** [comment]
I'll try to get my test setup going this week and run through some testing too. I'm hoping to add some features that make it easier to do testing in a large group. Dan Held wants to do a meetup in SF and it would be nice if they could test the return receipt version.

**Comment by remyers** [comment]
I've continued to hack on this and found and fixed some issues. I think the best thing would be for me to organize some small groups to test it and shake out problems before I do another PR.

Unfortunately my checkin discipline has not been so great so making individual PRs for my changes and fixes will take some work too.

I'll keep you posted.

**Comment by remyers** [comment]
More changes from my testing and feedback from meetup in New York. A few notable changes:
  - normal SDK tokens will broadcast 1 hop (ht Rich D)
  - Do not automatically pair with random nearby goTennas, sticky with last paired device
  - don't change GID every time you go to the settings menu
  - changed Android Manifest to use  android:launchMode="singleTop"

**Comment by SamouraiDev** [comment]
Will be merging shortly and updating Play APK. Thank you.

**Pull request merged**
